# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "sigstore-github-example"
      
    permissions:
      contents: read
      packages: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
     
        
      - name: "Docker Build"
        uses:  docker/setup-buildx-action@v1.6.0
        
      - name: "Log into the registry"
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.username}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: "Build and push docker images"
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{env.REGISTRY}}/${{secrets.username}}/${{env.IMAGE_NAME}}:${{github.run_id}}
      
      - name: "Install Cosign"
        uses: sigstore/cosign-installer@main
        
      - name: "Create cosign key"  
        env:
          COSIGN_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
        run: |
          echo "$COSIGN_KEY" && \
          echo "${{secrets.COSIGN_PRIVATE_KEY}}" && \
          echo "$COSIGN_KEY" > cosign.key
          
        
          
      - name: "Sign the image"  
        env:
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
          TAGS: ${{env.REGISTRY}}/${{secrets.username}}/${{env.IMAGE_NAME}}:${{github.run_id}}
        run: cosign sign --key cosign.key ${TAGS}
        
      
        
      
      
      
     
     
